### ISSUE TITLE
Uncaught TypeError: fileInput.click is not a function

### ISSUE THREAD

**Issue by joaomcarlos** [praneybehl/meteor-react-dropzone#1]
Hello.

Whenever I (or the plugin itself) calls the onClick, it will throw out that error.

Related to the function

```
this.refs.dropzone.open();
```

**Comment by praneybehl** [comment]
It seems that the function does exists : 
    https://github.com/paramaggarwal/react-dropzone/blob/master/index.js#L114

Can you please give an example how are you trying to implement?

**Comment by joaomcarlos** [comment]
Hello.

Inside this function, it will state that 'fileInput.click()' is not a function.

```
open() {
    var fileInput = this.refs.fileInput;
    fileInput.value = null;
    fileInput.click();
  }
```

I am using it like this : 

```
...
    dropZoneClick(){
        this.refs.dropzone.open();
    },
...
```

```
....


                    <Dropzone
                        ref="dropzone"
                        onClick={this.dropZoneClick}
                        onDrop={this.dropZoneDrop}
                        className="drop-area__newitem">
                        <div className="plus">+</div>
                    </Dropzone>
....
```

Everything works perfectly by the way, except the onClick, I can drop anything in and it will handle it perfectly, even ... 700 files :P 

![Example](http://g.recordit.co/P9Jmc4nSbv.gif)

If this helps:

Uncaught TypeError: fileInput.click is not a functionopen @ index.js:133onClick @ index.js:126executeDispatch @ react.browserify.js:3351SimpleEventPlugin.executeDispatch @ react.browserify.js:17627forEachEventDispatch @ react.browserify.js:3339executeDispatchesInOrder @ react.browserify.js:3360executeDispatchesAndRelease @ react.browserify.js:2727forEachAccumulated @ react.browserify.js:19658EventPluginHub.processEventQueue @ react.browserify.js:2934runEventQueueInBatch @ react.browserify.js:11172ReactEventEmitterMixin.handleTopLevel @ react.browserify.js:11198handleTopLevelImpl @ react.browserify.js:11284Mixin.perform @ react.browserify.js:18604ReactDefaultBatchingStrategy.batchedUpdates @ react.browserify.js:9612batchedUpdates @ react.browserify.js:16619ReactEventListener.dispatchEvent @ react.browserify.js:11378
2015-11-19 12:55:50.101 index.js:133 Uncaught TypeError: fileInput.click is not a functionopen @ index.js:133onClick @ index.js:126executeDispatch @ react.browserify.js:3351SimpleEventPlugin.executeDispatch @ react.browserify.js:17627forEachEventDispatch @ react.browserify.js:3339executeDispatchesInOrder @ react.browserify.js:3360executeDispatchesAndRelease @ react.browserify.js:2727forEachAccumulated @ react.browserify.js:19658EventPluginHub.processEventQueue @ react.browserify.js:2934runEventQueueInBatch @ react.browserify.js:11172ReactEventEmitterMixin.handleTopLevel @ react.browserify.js:11198handleTopLevelImpl @ react.browserify.js:11284Mixin.perform @ react.browserify.js:18604ReactDefaultBatchingStrategy.batchedUpdates @ react.browserify.js:9612batchedUpdates @ react.browserify.js:16619ReactEventListener.dispatchEvent @ react.browserify.js:11378

**Comment by praneybehl** [comment]
Just added it to an existing app to text and it seems to work great at my end. 
Here : 
![ScreenShot](http://g.recordit.co/DaL02EtdGy.gif)

**Comment by joaomcarlos** [comment]
I am puzzled.

I will try to figure it out on my end. I have absolutely no idea why this happens at the moment.

PS: what editor is that? Looks sexy, is it Atom? (what theme?)

**Comment by praneybehl** [comment]
Yes its Atom, the theme I am using is One Dark.
To what I can understand of your issue, somehow your DOM .click() function is blocked, it might be due a clash caused by another package.

Do you mind publishing the packages you are using?

**Comment by joaomcarlos** [comment]
Hello.

Somehow I missed your message, then life got in the way.

To honor your request: 

# Meteor packages used by this project, one per line.

# Check this file (and the other files in this directory) into your repository.

#

# 'meteor add' and 'meteor remove' will edit this file for you,

# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

insecure                # Allow all DB writes from clients (for prototyping)
semantic:ui
flemay:less-autoprefixer
dburles:collection-helpers
matb33:collection-hooks
reywood:publish-composite
yasinuslu:blaze-meta
alanning:roles
dburles:factory
stevezhu:lodash
accounts-password
reactive-var
natestrauser:animate-css
momentjs:moment

#testing..
#velocity:html-reporter
#xolvio:cucumber

reactive-dict
kadira:flow-router
#kadira:blaze-layout
#meteorhacks:kadira
#meteorhacks:zones
#meteorhacks:kadira-profiler
react
#kadira:flow-router-ssr
kadira:react-layout
meteortoys:allthings
praneybehl:react-dropzone

cfs:standard-packages
cfs:gridfs
cfs:graphicsmagick
browser-policy

**Comment by praneybehl** [comment]
Sorry mate but I can't figure what's wrong with your setup

**Comment by joaomcarlos** [comment]
I fixed it using jQuery like this (Meteor has jQuery by default so theres no reason not to use it) :

```
 open() {
        let fileInput = $(React.findDOMNode(this.refs.fileInput));
        fileInput.val(null);
        fileInput.trigger('click');
    },
```

**Comment by praneybehl** [comment]
Glad you did.
