### ISSUE TITLE
Atmosphere Mislinked

### ISSUE THREAD

**Issue by firrae** [praneybehl/meteor-react-dropzone#2]
Hi there,

I was just looking on Atmosphere at the react-notification package and I noticed that it's GitHub links point to this repo. I'm assuming this is a mistake and figured I'd let you know. Otherwise good work and creating React wrappers for these, they've been handy.

**Comment by praneybehl** [comment]
Thanks for the report, for some reason meteor cli tool would not let me update the package I am investigating.

**Comment by firrae** [comment]
For my package I had to bump the version number to do a small update, not
sure what the issue is you're seeing though.

**Comment by praneybehl** [comment]
Fixed the issue also bumped v3.0.3 of source. Thanks for your patience.

**Comment by firrae** [comment]
Not a problem, thanks a bunch!
