### ISSUE TITLE
Dropzone does not accept onClick prop

### ISSUE THREAD

**Issue by joaomcarlos** [praneybehl/meteor-react-dropzone#3]
Hello.

I noticed that the Dropzone does not accept a onClick prop so I cant override it.

Can you please implement it? So I can re-route the onClick for the Dropzone.

**Comment by joaomcarlos** [comment]
Here is how: 

```
class Dropzone extends React.Component {
  ....
onClick() {
        if (!this.props.disableClick) {
            if(this.props.onClick)
                this.props.onClick(this);
            else
                this.open();
        }
    },
....
  }
```

**Comment by praneybehl** [comment]
PRs are welcome.

**Comment by joaomcarlos** [comment]
This doesnt have any "code", so I cant just submit a PR, sorry.

**Comment by praneybehl** [comment]
As mentioned in the package ReadMe, this package is only a wrapper around https://github.com/paramaggarwal/react-dropzone so please submit your feature requests to the main repo as above. 
Thanks

**Comment by praneybehl** [comment]
I am closing this since its not related to the meteor package itself.
